spring:
  application:
    name: Skeleton
  datasource:
    url: jdbc:postgresql://localhost:5432/interview
    username: interview
    password: interview
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc.insert_returning.enabled: false

